### ISSUE TITLE
Annotate outlier analysis with available pathology stains

### ISSUE THREAD

**Issue by mokolodi1** [UCSC-MedBook/MedBook-PatientCare#30]
See "Fwd: Stanford list: Pathology tests" email on July 7th.

**Comment by e-t-k** [comment]
"Is it possible to annotate whether the upregulated outliers and top 5% expressed genes are found in this list of available pathology stains? We could say "Stanford pathology stain available" next to a gene if it is in this list. Please note that some of these gene names would require manual conversion since they are really protein names."

Priority : after top5% expressed genes functionalities

**Comment by e-t-k** [comment]
Currently on staging.

_fixed by ed36f65_  ~~Tooltips are weirdly inconsistent.~~ 

All tooltips work when genes are in the top5% ; for up & down outliers, the 2 "Tree" tooltips work but the other two do not popup (despite appearing in the DOM correctly.)

**Comment by e-t-k** [comment]
check onRendered code for where tooltips appear. above was an artifact of the square & star tooltips all having been added on genes that are displayed when page is first loaded and not only appearing when additional genes displayed.

**Comment by e-t-k** [comment]
Ready for final code review before pushing to prod -- @mokolodi1 when you have a moment can you check? pull request #75 [ ETA: replaced by pull request #77]

**Comment by mokolodi1** [comment]
lgtm!

**Comment by e-t-k** [comment]
This is now live. There's yet another tooltip bug but I'm making a new issue (#87). Visible tooltips can be updated via medbook UI by deleting and recreating the correct GeneSetGroup.
